name:                hs-solver
version:             0.1.0.0
github:              "cloudy-marti/INFO_Haskell_Project"
license:             BSD3
author:              "Vincent AGULLO & Emilie MARTI"
maintainer:          "Vincent AGULLO & Emilie MARTI"
copyright:           "2020 Vincent Agullo & Emilie Marti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A project about handling and transformation of logical formulas using Haskell.
category:            Mathematical logic

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cloudy-marti/INFO_Haskell_Project#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- split >= 0.2

library:
  source-dirs: src
  exposed-modules:
    - Data.Logic.Combinator
    - Data.Logic.Var
    - Data.Logic.Fml

tests:
  hs-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-solver
    - test-framework
    - test-framework-hunit
    - HUnit
